name: Build and Deploy to Google Play

on:
  push:
    branches:
      - automate

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Give Permission
      run: chmod +x ./gradlew
      
    - name: Build with Gradle
      run: ./gradlew clean assembleRelease bundleRelease

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: sample_automation  # Nama Artifact
        path: app/release/
    - name: Debug Output
      run: |
        ls -R app/build/outputs/
        ls -R app/build/outputs/apk/release/
        
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Sign APKs
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: app/release/
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
        
  release:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
    - name: Download APK from build
      uses: actions/download-artifact@v1
      with:
        name: sample_automation  # Nama Arifact
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.event.inputs.version }}
        name: Release v${{ github.event.inputs.version }}
        draft: false
        prerelease: false
        files: app/release/sample_automation.apk
